variables:
  SERVICE_NAME: payment-service
  SERVICE_IMAGE: "localhost:5000/payment-service"

build-payment-service:
  stage: build
  script:
    - |
      docker build \
        -f payment-service/Dockerfile \
        -t "${SERVICE_IMAGE}:${CI_COMMIT_SHORT_SHA}" \
        .
    - docker push "${SERVICE_IMAGE}:${CI_COMMIT_SHORT_SHA}"

deploy-payment-service:
  stage: deploy
  script:
    - |
      helm upgrade --install ${SERVICE_NAME} ./helm/${SERVICE_NAME} \
        --set image.tag="${CI_COMMIT_SHORT_SHA}"