apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config

data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}